global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:3000']
  - job_name: 'auth-iam'
    static_configs:
      - targets: ['auth-iam:3001']
  - job_name: 'zone-policy'
    static_configs:
      - targets: ['zone-policy:3002']
  - job_name: 'device-management'
    static_configs:
      - targets: ['device-management:3003']
  - job_name: 'content-service'
    static_configs:
      - targets: ['content-service:3004']
  - job_name: 'schedule-service'
    static_configs:
      - targets: ['schedule-service:3005']
  - job_name: 'sync-service'
    static_configs:
      - targets: ['sync-service:3006']
  - job_name: 'validation-qa'
    static_configs:
      - targets: ['validation-qa:3007']
  - job_name: 'signing-kms'
    static_configs:
      - targets: ['signing-kms:3008']
  - job_name: 'audit-service'
    static_configs:
      - targets: ['audit-service:3009']
